### ISSUE TITLE
Cannot find package with go build

### ISSUE THREAD

**Issue by IreneZihuiLi** [facebookresearch/Clinical-Trial-Parser#1]
`go build ./...` under the Clinical-Trial-Parser path, I go the following error:

`src/cmd/cfg/main.go:13:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf (from $GOPATH)
src/cmd/cfg/main.go:14:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/param" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/param (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/param (from $GOPATH)
src/cmd/cfg/main.go:15:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/fio" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/fio (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/fio (from $GOPATH)
src/cmd/cfg/main.go:16:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/timer" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/timer (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/timer (from $GOPATH)
src/cmd/cfg/main.go:17:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/ct/studies" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/studies (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/studies (from $GOPATH)
src/cmd/cfg/main.go:18:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/ct/units" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/units (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/units (from $GOPATH)
src/cmd/cfg/main.go:19:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/ct/variables" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/variables (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/variables (from $GOPATH)
src/cmd/cfg/main.go:21:2: cannot find package "github.com/golang/glog" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/golang/glog (from $GOROOT)
	/Users/ireneli/.go/src/github.com/golang/glog (from $GOPATH)
src/cmd/nel/main.go:14:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/set" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/set (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/set (from $GOPATH)
src/cmd/nel/main.go:18:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/slice" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/slice (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/slice (from $GOPATH)
src/cmd/nel/main.go:20:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies (from $GOPATH)
src/cmd/nel/main.go:21:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/mesh" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/mesh (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/mesh (from $GOPATH)
src/cmd/nel/main.go:22:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/taxonomy" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/taxonomy (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/taxonomy (from $GOPATH)
src/cmd/nel/main.go:23:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/umls" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/umls (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/umls (from $GOPATH)
src/common/col/tuple/tuple.go:10:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/intmath" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/intmath (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/intmath (from $GOPATH)
src/common/conf/conf.go:14:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/resource" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/resource (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/resource (from $GOPATH)
src/common/lsh/minhash.go:13:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/tuple" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/tuple (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/tuple (from $GOPATH)
src/common/util/text/text.go:13:2: cannot find package "golang.org/x/text/transform" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/golang.org/x/text/transform (from $GOROOT)
	/Users/ireneli/.go/src/golang.org/x/text/transform (from $GOPATH)
src/common/util/text/text.go:14:2: cannot find package "golang.org/x/text/unicode/norm" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/golang.org/x/text/unicode/norm (from $GOROOT)
	/Users/ireneli/.go/src/golang.org/x/text/unicode/norm (from $GOPATH)
src/ct/criteria/parse_criteria.go:9:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/text" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/text (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/text (from $GOPATH)
src/ct/criteria/criteria.go:9:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/ct/relation" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/relation (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/relation (from $GOPATH)
src/ct/parser/interpreter.go:6:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser/production" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser/production (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser/production (from $GOPATH)
src/ct/studies/study.go:11:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/ct/criteria" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/criteria (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/criteria (from $GOPATH)
src/ct/studies/study.go:12:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser (from $GOPATH)
src/ct/units/units.go:13:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/trie" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/trie (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/trie (from $GOPATH)
src/vocabularies/taxonomy/node.go:12:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/lsh" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/lsh (from $GOROOT)
	/Users/ireneli/.go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/lsh (from $GOPATH)`

Do I need to change GOPATH? 

Thanks.

**Comment by salkola** [comment]
A likely explanation is that GOPATH and the project workspace don't match. Set GOPATH to a directory where you would like to have the project code. Clone the project to `$GOPATH/src/github.com/facebookresearch/Clinical-Trial-Parser`. More about go workspaces: https://golang.org/doc/gopath_code.html

Within the project, you may need to add dependencies by running the command `go get -u ./...`
You may also need to run the command `go get github.com/stretchr/testify/assert` and install Xcode for Mac OS X, if it is not pre-installed.

**Comment by salkola** [comment]
Resolved.

**Comment by celwell-reify** [comment]
I also had to ran `go mod init` and `go mod tidy` in the root dir. I'm very new to Go, so maybe this is something that's implied in the docs.
