### ISSUE TITLE
issues with "go build ./..."

### ISSUE THREAD

**Issue by jingcheng-du** [facebookresearch/Clinical-Trial-Parser#11]
Thanks for sharing the codes. However, I was not able to run go build. I installed "go" from https://golang.org/dl/, and cd Clinical-Trial-Parser. Do you have more guidance on how to setup $GOPATH? Thanks!

src/cmd/cfg/main.go:13:2: cannot find package "github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf" in any of:
	/usr/local/go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf (from $GOROOT)
	/Users/xxx/go/src/github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf (from $GOPATH)

**Comment by salkola** [comment]
Yes, please see the [developer guide](https://github.com/facebookresearch/Clinical-Trial-Parser/blob/master/doc/developer_guide.md) or #1.

**Comment by jingcheng-du** [comment]
thank you!
