### ISSUE TITLE
No parsing of nominal criteria?

### ISSUE THREAD

**Issue by kevinwu23** [facebookresearch/Clinical-Trial-Parser#14]
The README describes nominal criteria as the most common, and yet in the test example, there appear to be none. Is there an issue with the way I am running the script or is this expected behavior?

**Comment by salkola** [comment]
You are probably doing nothing wrong.  [cfg_parse.sh](https://github.com/facebookresearch/Clinical-Trial-Parser/blob/master/script/cfg_parse.sh) yields ordinal and numerical criteria relations. [ie_parse.sh](https://github.com/facebookresearch/Clinical-Trial-Parser/blob/master/script/ie_parse.sh) extracts nominal variable names. Please see the [general section](https://github.com/facebookresearch/Clinical-Trial-Parser/blob/master/doc/architecture.md#general) of the architecture document.

**Comment by kevinwu23** [comment]
Thanks for the help.
I see that one of the TODO is "Post process IE relations and merge with CGF results"
What general steps do you have in mind in terms of post-processing IE relations?
I'm probably going to write something for myself, and can try to push something if this hasn't been done yet.

**Comment by salkola** [comment]
I look forward to your contributions.

[Post processing](https://github.com/facebookresearch/Clinical-Trial-Parser/blob/master/doc/architecture.md#pre-and-post-processing) includes removing duplicate criteria relations and making sure that the extracted relations are valid and consistent with each other.

Depending on your need, a good place to start might be implementing a [negation](https://github.com/facebookresearch/Clinical-Trial-Parser/blob/master/doc/architecture.md#negation) module for the IE parser.
