### ISSUE TITLE
ImportError: cannot import name 'metanet_pb2' from partially initialized module 'caffe2.proto'

### ISSUE THREAD

**Issue by bhomass** [facebookresearch/Clinical-Trial-Parser#22]
I have been trying to get this lib to work for three days. I have tried python 3.5, 3.6, 3.7, and 3.10.
I have tried installing pytext using conda, pip, and build from source. 

It all ends up with the error in the issue title. 
    from caffe2.proto import caffe2_pb2
  File "/data/anaconda3/envs/pytext/lib/python3.8/site-packages/caffe2/proto/__init__.py", line 15, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'metanet_pb2' from partially initialized module 'caffe2.proto'

googling ends up in dead trails where people continue to see the same problem, but previously raised tickets are closed. 

Please give indication how to get past this step?

**Comment by salkola** [comment]
I use Python 3.7.6. I have not seen this error before. Only advice I can give is to do a clean install by deleting previous packages. Maybe use a new Python environment to install everything?
