### ISSUE TITLE
Is it possible to deploy the Clinical Trial Parser as a docker container

### ISSUE THREAD

**Issue by srinhari** [facebookresearch/Clinical-Trial-Parser#25]
Is it possible to deploy the Clinical Trial Parser as a docker container?

**Comment by salkola** [comment]
It could be possible to publish a Docker image to Docker Hub or GitHub Packages, although I have not tried it.

**Comment by ziviprotech** [comment]
Clinical Trial Parser mostly uses Go and Python. You should be able to create Docker for Go as mentioned here: https://hub.docker.com/_/golang. After that you can install python related stuff.

**Comment by srinhari** [comment]
Thank you @salkola and @pmittal77 . Will explore these options.
