### ISSUE TITLE
Cannot find resource path

### ISSUE THREAD

**Issue by mlaria** [facebookresearch/Clinical-Trial-Parser#4]
I was able to build, test, and train NER model as described in the README page. But when I try to run  ./script/cfg_parse.sh, I get the following error:

```
I0513 09:01:33.759475   46288 conf.go:72] src/resources/config/cfg.conf: Lines: 6, Parameters: 2
F0513 09:01:33.759589   46288 resource.go:37] Cannot find resource path for "/github.com/facebookresearch/Clinical-Trial-Parser/src/resources"
exit status 255
CFG parser failed.
```
Any idea how to fix this?

**Comment by salkola** [comment]
Because NEL uses Go, the GOPATH environment variable needs to be set to a directory where the project workspace is located. Set GOPATH so that the cloned project is in $GOPATH/src/github.com/facebookresearch/Clinical-Trial-Parser.

**Comment by mlaria** [comment]
Thanks! that solved the issue.
