### ISSUE TITLE
Facing the following error when running ./script/cfg_parse.sh 

### ISSUE THREAD

**Issue by anirbanmishra** [facebookresearch/Clinical-Trial-Parser#8]
Clinical-Trial-Parser amishr02$ ./script/cfg_parse.sh 
src/common/resource/resource.go:10:2: cannot find package "github.com/golang/glog" in any of:
	/usr/local/go/src/github.com/golang/glog (from $GOROOT)
	/Users/amishr02/PycharmProjects/Clinical-Trials/src/github.com/golang/glog (from $GOPATH)
src/common/util/text/text.go:13:2: cannot find package "golang.org/x/text/transform" in any of:
	/usr/local/go/src/golang.org/x/text/transform (from $GOROOT)
	/Users/amishr02/PycharmProjects/Clinical-Trials/src/golang.org/x/text/transform (from $GOPATH)
src/common/util/text/text.go:14:2: cannot find package "golang.org/x/text/unicode/norm" in any of:
	/usr/local/go/src/golang.org/x/text/unicode/norm (from $GOROOT)
	/Users/amishr02/PycharmProjects/Clinical-Trials/src/golang.org/x/text/unicode/norm (from $GOPATH)
CFG parser failed.

I know I am missing something but cannot figure it out.

**Comment by salkola** [comment]
Your GOPATH may be set incorrectly. Please see the [developer guide](https://github.com/facebookresearch/Clinical-Trial-Parser/blob/master/doc/developer_guide.md) or [Issue #1](https://github.com/facebookresearch/Clinical-Trial-Parser/issues/1).

**Comment by anirbanmishra** [comment]
My GOPATH is set as follows 
echo $GOPATH
/Users/amishr02/PycharmProjects/Clinical-Trials 
and I cloned the directory to:
$GOPATH/src/github.com/facebookresearch/Clinical-Trial-Parser

**Comment by salkola** [comment]
That looks good. Have you run `go get -u ./...` in the project root directory ($GOPATH/src/github.com/facebookresearch/Clinical-Trial-Parser)?
