### ISSUE TITLE
looping trying to add package 

### ISSUE THREAD

**Issue by iamyihwa** [facebookresearch/Clinical-Trial-Parser#9]
Hello, I had an error that was similar to the one mentioned [here](https://github.com/facebookresearch/Clinical-Trial-Parser/issues/8). 
However after running  ```go get -u ./... ```,  I get following error 'go: github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/cfg: looping trying to add package',

**Comment by salkola** [comment]
Does `go get ./...` give the same error?

I updated my Go to version go1.14.4, but it does not reproduce your problem.

**Comment by iamyihwa** [comment]
Yes it gives same error message.  
I just noticed that perhaps other materials were also missing 
This below is the entire error message. 
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/slice
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/resource
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/taxonomy
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/timer
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/lsh
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/intmath
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/units
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/fio
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/variables
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/set
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/param
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/search
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/tuple
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/studies
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/mesh
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/eligibility
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/umls
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/text
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/nel
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/trie
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser/production
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/criteria
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/relation
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/extract
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/cfg
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/eligibility
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/param
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/timer
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/taxonomy
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/lsh
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/set
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/extract
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/units
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/conf
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/umls
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/search
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/col/tuple
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/variables
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/cfg
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/resource
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/parser/production
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/trie
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/intmath
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/nel
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/relation
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/criteria
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/fio
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/vocabularies/mesh
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/slice
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/common/util/text
go: finding module for package github.com/facebookresearch/Clinical-Trial-Parser/src/ct/studies
go: github.com/facebookresearch/Clinical-Trial-Parser/src/cmd/cfg: looping trying to add package

**Comment by salkola** [comment]
I assume ` go buid ./...` etc. won't work either. Are you able to run any other go programs?

Go had the following issue: https://github.com/golang/go/issues/30394. I wonder if updating your Go version and cleaning up the packages would help. In addition, I can only suggest to delete the project, to clone it again, and to make sure that Go is setup properly.

**Comment by iamyihwa** [comment]
I have installed the most recent version (1.14.4) as was in [here](https://golang.org/dl/), and followed the instructions [here](https://golang.org/doc/install) to set up.
I could run hello world example (also from above instruction to set up page example).. 
```
cdsw@9tdvk9bwif7uyk7n:~$ go build hello.go
cdsw@9tdvk9bwif7uyk7n:~$ ./hello
hello, world
```

What do you mean by go setup properly? 

Currently go is set up at ~/local/go/bin  
```
cdsw@9tdvk9bwif7uyk7n:~/local/go$ which go
/home/cdsw/local/go/bin/go
```
and Clinical Trial Parser is at ~/local/go/src/github.com/facebookresearch/Clinical-Trial-Parser
```
cdsw@9tdvk9bwif7uyk7n:~/local/go/src/github.com/facebookresearch/Clinical-Trial-Parser$ ls
bin  CODE_OF_CONDUCT.md  CONTRIBUTING.md  data  doc  LICENSE  README.md  script  src
```

GOPATH is set up such that 
```
cdsw@9tdvk9bwif7uyk7n:~/local/go/src/github.com/facebookresearch/Clinical-Trial-Parser$ printenv GOPATH
/home/cdsw/local/go
```

I just set things up on Monday and I don't know how I can do things differently.

**Comment by salkola** [comment]
That looks ok. You could try Installing Go somewhere else than in /home/cdsw/local/go because your workspace is also in /home/cdsw/local/go. Would installing Go in /usr/local/go (=GOROOT) help?

**Comment by iamyihwa** [comment]
The thing is I cannot install at /usr/local due to permission issue. 
I have instead set the GOROOT also 
```
cdsw@13bibixulsfuz8ec:~/local$ printenv GOROOT
/home/cdsw/local/go
```

However am getting the same error.

**Comment by salkola** [comment]
I can reproduce your problem when I install Go in the Go workspace. To fix this, you could, for example, set up your directories so that `GOROOT=/home/cdsw/tools/go` and `GOPATH=/home/cdsw/workspaces/go` (or /home/cdsw/local/...).  In addition, you may have to clean up `/home/cdsw/local/go`.

**Comment by iamyihwa** [comment]
Thank you @salkola!  Issue got solved!! I will close the issue thank you for the help!
